### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jacobthetechy** [hgrecco/mdform#1]
Could you please add some more examples or a minimal working code to the documentation? I'm having a hard time trying to figure out how to use this withing a project.

Thanks!

**Comment by hgrecco** [comment]
I will upload a Flask Extension on the weekend that demonstrate how to use it. Stay tuned

**Comment by jacobthetechy** [comment]
Awesome! Looking forward to it.

**Comment by hgrecco** [comment]
Take a look at the examples here:

https://github.com/hgrecco/flask-mdform
